<?php 
define('TITULO_SITIO','TIENDA DE OFERTAS');
define('CONTRASENIA_LONGITUD_MINIMA',8);
define('CONTRASENIA_LONGITUD_MAXIMA',15);
define('FORMATO_FECHA_HORA', 'Y-m-d H:i:s');
define('OFFERCRIPS_INICIAL',10000);
define('VALOR_OFFERCRIP', 5);

?>